///////////////////////////////////////////////////////////////////////////////
// RobotArmMain.cpp
#include "TcPch.h"
#pragma hdrstop

#include "RobotArmMain.h"
#include "3rdinterpolate.h"
#include "kinematics.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// CRobotArmMain
///////////////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CRobotArmMain
BEGIN_INTERFACE_MAP(CRobotArmMain)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_ITcCyclic, ITcCyclic)
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_ITCOMOBJECT(CRobotArmMain)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CRobotArmMain)
IMPLEMENT_ITCADI(CRobotArmMain)
IMPLEMENT_ITCWATCHSOURCE(CRobotArmMain)


///////////////////////////////////////////////////////////////////////////////
// Set parameters of CRobotArmMain 
BEGIN_SETOBJPARA_MAP(CRobotArmMain)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
	SETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	SETOBJPARA_VALUE(PID_RobotArmMainParameter, m_Parameter)
	SETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CRobotArmMain 
BEGIN_GETOBJPARA_MAP(CRobotArmMain)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
	GETOBJPARA_VALUE(PID_TcTraceLevel, m_TraceLevelMax)
	GETOBJPARA_VALUE(PID_RobotArmMainParameter, m_Parameter)
	GETOBJPARA_ITFPTR(PID_Ctx_TaskOid, m_spCyclicCaller)
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CRobotArmMain
BEGIN_OBJPARAWATCH_MAP(CRobotArmMain)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CRobotArmMain
BEGIN_OBJDATAAREA_MAP(CRobotArmMain)
///<AutoGeneratedContent id="ObjectDataAreaMap">
	OBJDATAAREA_VALUE(ADI_RobotArmMainInputs, m_Inputs)
	OBJDATAAREA_VALUE(ADI_RobotArmMainOutputs, m_Outputs)
	OBJDATAAREA_VALUE(ADI_RobotArmMainPlcToCpp, m_PlcToCpp)
	OBJDATAAREA_VALUE(ADI_RobotArmMainCppToPlc, m_CppToPlc)
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
CRobotArmMain::CRobotArmMain()
	: m_Trace(m_TraceLevelMax, m_spSrv)
	, pi(3.14159)
{
///<AutoGeneratedContent id="MemberInitialization">
	m_TraceLevelMax = tlAlways;
	memset(&m_Parameter, 0, sizeof(m_Parameter));
	memset(&m_Inputs, 0, sizeof(m_Inputs));
	memset(&m_Outputs, 0, sizeof(m_Outputs));
	memset(&m_PlcToCpp, 0, sizeof(m_PlcToCpp));
	memset(&m_CppToPlc, 0, sizeof(m_CppToPlc));
///</AutoGeneratedContent>
}

///////////////////////////////////////////////////////////////////////////////
CRobotArmMain::~CRobotArmMain() 
{
}


///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CRobotArmMain)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CRobotArmMain::SetObjStatePS(PTComInitDataHdr pInitData)
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);

	// TODO: Add initialization code

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CRobotArmMain::SetObjStateSO()
{
	m_Trace.Log(tlVerbose, FENTERA);
	HRESULT hr = S_OK;

	// TODO: Add any additional initialization


	// If following call is successful the CycleUpdate method will be called, 
	// possibly even before method has been left.
	hr = FAILED(hr) ? hr : AddModuleToCaller(); 

	// Cleanup if transition failed at some stage
	if ( FAILED(hr) )
	{
		RemoveModuleFromCaller(); 
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CRobotArmMain::SetObjStateOS()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;

	RemoveModuleFromCaller(); 

	// TODO: Add any additional deinitialization

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CRobotArmMain::SetObjStateSP()
{
	HRESULT hr = S_OK;
	m_Trace.Log(tlVerbose, FENTERA);

	// TODO: Add deinitialization code

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

//运动规划测试数据
//TODO:将数组改为结构体，提高程序可读性
double KinematicsData[3][5] = { { 681, 0, 0, 1, 1 }, 
								{ 455.4320, 474.8313, 90, 6, 11 }, 
								{ 681, 0, 0, 19, 1e4 } };				//反解数据值：Ax, Ay, Aphi, t0, tf
double CurrentPositionData[3] = { 0 };									//当前的反解角度值: 肩、肘、腕
double NextPositionData[3] = { 0 };										//下一个位置的反解角度值: 肩、肘、腕
//double PolynomialData[2][6] = { { 0, 0, 0, 0, 0, 6 }, { 0, 0, 0, 0, 11, 19 } };			//插值公式参数：三次项系数，二次项系数，一次项系数，零次项系数，T0, Tf
int PositionSize = 3 - 1;
int PositionNum = 0;
int PositionStatus = 0;

///<AutoGeneratedContent id="ImplementationOf_ITcCyclic">
HRESULT CRobotArmMain::CycleUpdate(ITcTask* ipTask, ITcUnknown* ipCaller, ULONG_PTR context)
{
	HRESULT hr = S_OK;

	// TODO: Replace the sample with your cyclic code

	UpdateInputs();
	//TODO:初始化肘关节，位置初始化，角度初始化
	if ((m_PlcToCpp.PlcStarted == true) && (m_PlcToCpp.ShoudlerInitFinish == true) && (m_PlcToCpp.LevelShiftExtEnabled == true))
	{
		if ((timer > 0.5) && (timer < 1))      //肘关节初始化
		{
			elbow.SetTargetAngle(0);
			elbow.run();
		}
		else
		{
			if (PositionNum < PositionSize)
			{
				switch (PositionStatus)
				{
				case 0:	//反解角度，计算插值函数
					if (PositionNum == 0)
					{
						//初始状态逆解
						kinematics_inverse(
							KinematicsData[0][0],
							KinematicsData[0][1],
							KinematicsData[0][2],
							CurrentPositionData);
					}
					kinematics_inverse(
						KinematicsData[PositionNum + 1][0],
						KinematicsData[PositionNum + 1][1],
						KinematicsData[PositionNum + 1][2],
						NextPositionData);
					//肘关节平移
					ElbowPolynomial.plan3rdProfileT(
						KinematicsData[PositionNum][4],
						KinematicsData[PositionNum + 1][3],
						CurrentPositionData[1],
						NextPositionData[1],
						0, 0);
					//肩关节平移
					ShoulderLevelShiftPolynomial.plan3rdProfileT(
						KinematicsData[PositionNum][4],
						KinematicsData[PositionNum + 1][3],
						CurrentPositionData[0],
						NextPositionData[0],
						0, 0);
					PositionStatus = 1;
					//这里不需要加break，计算完插值表达式后就进入case1，给定角度。
				case 1:
					if ((timer > KinematicsData[PositionNum][4]) && (timer < KinematicsData[PositionNum + 1][3]))
					{
						double SetElbowAngle = ElbowPolynomial.pos(timer);
						elbow.SetTargetAngle(SetElbowAngle);
						elbow.run();

						TarPosLevelShift = ShoulderLevelShiftPolynomial.pos(timer) / 90.0 * 23.0;

					}
					else if (timer > KinematicsData[PositionNum + 1][3])
					{
						/*单步调试结束，取消下面判断的注释*/
						if (fabs_(elbow.ShowAngle() - NextPositionData[1]) > 0.1)		//判断是否走到期望位置，若没有，报错。
						{
							PositionStatus = 3;
						}
						else if (fabs_(elbow.ShowAngle() - NextPositionData[1]) < 0.1)	//这里判断方式有问题，因为角度可能存在超调，将会在第一次到达时认为到达目标点，而不是在稳定后认为到达目标点。
						{
							PositionStatus = 0;
							PositionNum++;
							for (int i = 0; i < 3; i++)
							{
								CurrentPositionData[i] = NextPositionData[i];
							}
						}
						//TODO:验证其他关节是否达到期望位置
					}
					break;
				case 3://错误处理
					break;
				default:
					break;
				}
			}
		}
		UpdateOutputs();
	}
	return hr;
}
///</AutoGeneratedContent>

void CRobotArmMain::UpdateInputs()
{
	timer = m_PlcToCpp.Timer;
	ElbowUpdateInputs();

	ShoulderElbowUpdateInputs();
}

void CRobotArmMain::UpdateOutputs()
{
	ElbowUpdateOutputs();

	ShoulderUpdateOutputs();
}

void CRobotArmMain::ElbowUpdateInputs()
{
	//if (m_PlcToCpp.ElbowAngle < 200)//旧的肘会出现过零点状况
	//{
	//	elbow.GetActualAngle(m_PlcToCpp.ElbowAngle + 360 - 261);
	//}
	//else if (m_PlcToCpp.ElbowAngle >= 200)
	//{
		elbow.GetActualAngle(m_PlcToCpp.ElbowAngle - 261);//不受力状态时，角度为261，减去，角度会增大//旧的肘
	//}

	//elbow.GetActualAngle(350 - m_Inputs.Angle);//不受力状态时，角度为350，减去，角度会减少//新的肘

}

void CRobotArmMain::ElbowUpdateOutputs()
{
	/* 输出给EL4004，用来控制比例压力阀。压力阀接收电压为0-10V */
	//电压转换为（0-10V）->（0-32767）
	if ((elbow.ShowM1() <= 3) && (elbow.ShowM2() <= 3))
	{
		m_Outputs.ElbowOutM1 = static_cast<int>(elbow.ShowM1() / 10.0 * 32767.0);
		m_Outputs.ElbowOutM2 = static_cast<int>(elbow.ShowM2() / 10.0 * 32767.0);
	}
	else
	{
		m_Outputs.ElbowOutM1 = 0;
		m_Outputs.ElbowOutM2 = 0;
	}

	///* 输出个PLC用来观察的 */
	//if (elbow.ShowAngle() > 0)
	{
		m_CppToPlc.ElbowTarAngle = elbow.ShowTarAngle();
		m_CppToPlc.ElbowAngle = elbow.ShowAngle();
	}
	//m_Outputs.m1v = elbow.ShowM1();
	//m_Outputs.m2v = elbow.ShowM2();
}

void CRobotArmMain::ShoulderElbowUpdateInputs()
{
	PosLevelShift = m_PlcToCpp.PosLevelShift;
	ShoulderInitFinish = m_PlcToCpp.ShoudlerInitFinish;
}

void CRobotArmMain::ShoulderUpdateOutputs()
{
	m_CppToPlc.TarPosLevelShift = TarPosLevelShift;
}

///////////////////////////////////////////////////////////////////////////////
HRESULT CRobotArmMain::AddModuleToCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);

	HRESULT hr = S_OK;
	if ( m_spCyclicCaller.HasOID() )
	{
		if ( SUCCEEDED_DBG(hr = m_spSrv->TcQuerySmartObjectInterface(m_spCyclicCaller)) )
		{
			if ( FAILED(hr = m_spCyclicCaller->AddModule(m_spCyclicCaller, THIS_CAST(ITcCyclic))) )
			{
				m_spCyclicCaller = NULL;
			}
		}
	}
	else
	{
		hr = ADS_E_INVALIDOBJID; 
		SUCCEEDED_DBGT(hr, "Invalid OID specified for caller task");
	}

	m_Trace.Log(tlVerbose, FLEAVEA "hr=0x%08x", hr);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
VOID CRobotArmMain::RemoveModuleFromCaller()
{
	m_Trace.Log(tlVerbose, FENTERA);

	if ( m_spCyclicCaller )
	{
		m_spCyclicCaller->RemoveModule(m_spCyclicCaller);
	}
	m_spCyclicCaller	= NULL;

	m_Trace.Log(tlVerbose, FLEAVEA);
}

